### ISSUE TITLE
Add support for IP ranges and importing its configuration from CSV

### ISSUE THREAD

**Issue by lubomirw** [CZERTAINLY/CZERTAINLY-IP-Discovery-Provider#33]
#### Add CSV import option to `IP-Hostname` kind with following structure:
- IP address or hostname
- comma separated ports. The delimiter in this case should be different than comma, for example pipe `|`

#### Add new kinds with following attributes and CSV import structure:

`IP-Range`

- Starting IP address
- Ending IP address
- Comma separated ports
- upload CSV option with the similar structure (ports delimited with pipe `|`)

`IP-Subnet`

- Subnet, for example `192.168.1.0/24`
- Comma separated ports
- upload CSV option with the similar structure (ports delimited with pipe `|`)

**Comment by 3keyroman** [comment]
@lubomirw The implementation in #57 adds possibility to use IP address range and port range for specific network discovery.
Using the same `IP-Hostname` kind. You can also combine input that is comma separate. So you can discover certificates for example on the following IPs and Hostnames:
```
www.example.com,192.168.1.1,10.1.1.20-10.1.1.50,172.16.1.0/24,172.16.1.0/24
```
And on the various ports:
```
443,80,8080,22,21,25,110,143,9000-10000
```

This has a greater flexibility on where user would like to run discovery. In connection with that, the kinds `IP-Range` or `IP-Subnet` will not be necessary.

And I think that we do not need to implement option to upload CSV. The CSV would be useful only in case I have multiple inputs where I would like to create different combination of IPs and ports. But you can always setup 2 different discovery processes which seems to be better to manage.

So I suggest to open new issue if the CSV will be needed.
